<div class="homeGrid">

  	<div class="item wi2 hi3 transparent"></div>
  	<div class="item wi1 hi2 transparent ignore-shuffle"></div>
    <div class="item wi2 hi1 transparent"></div>
  	<div class="item wi4 hi2 transparent ignore-shuffle"></div>
  	<div class="item wi3 hi1 transparent"></div>
  	<div class="item wi1 hi3 transparent ignore-shuffle"></div>
  	<div class="item wi2 hi2 transparent"></div>
    <div class="item wi2 hi4 transparent"></div>  	
    <div class="item wi4 hi1 transparent ignore-shuffle"></div>
  	<div class="item wi1 hi2 transparent ignore-shuffle"></div>
    <div class="item wi2 hi1 transparent"></div>
  	<div class="item wi4 hi2 transparent ignore-shuffle"></div>
  	<div class="item wi3 hi3 transparent"></div>
  	<div class="item wi4 hi1"></div>
  	<div class="item wi1 hi1 ignore-shuffle"></div>
    <div class="item wi1 hi1"></div> 	
    <div class="item wi2 hi3"></div>
  	<div class="item wi1 hi1 ignore-shuffle"></div>
    <div class="item wi2 hi1"></div>
  	<div class="item wi4 hi4 semi-transparent"></div>
  	<div class="item wi1 hi1"></div>
  	<div class="item wiHi hi1"></div>
  	<div class="item wi2 hi2"></div>
    <div class="item wi3 hi1"></div>  	
    <div class="item wi2 hi3"></div>
  	<div class="item wi1 hi1"></div>
    <div class="item wi2 hi1 semi-transparent"></div>
  	<div class="item wi4 hi4"></div>
  	<div class="item wi3 hi3"></div>
  	<div class="item wi1 hi3"></div>
  	<div class="item wi2 hi2 semi-transparent"></div>
  	<div class="item wi1 hi1"></div>
    <div class="item wi2 hi1"></div>
  	<div class="item wi4 hi4 semi-transparent"></div>
  	<div class="item wi1 hi1"></div>
  	<div class="item wiHi hi1"></div>
  	<div class="item wi2 hi2"></div>
    <div class="item wi3 hi1"></div>  	
    <div class="item wi2 hi3"></div>
  	<div class="item wi1 hi1"></div>
    <div class="item wi2 hi1 semi-transparent"></div>
  	<div class="item wi4 hi4"></div>
  	<div class="item wi3 hi3"></div>
  	<div class="item wi1 hi3"></div>
  	<div class="item wi2 hi2 semi-transparent"></div>
    <div class="item wi2 hi4"></div>

</div>
	
